baseURL = "https://cuanzhang.github.io/yoyo-blog/"
languageCode = "en-us"
title = "Yoyo's Blog"
theme = "PaperMod"
publishDir = "docs"

[pagination]
  pagerSize = 5

[params]
  defaultTheme = "auto"
  disableThemeToggle = false

  [params.homeInfoParams]
    Title = "Yoyo's Blog"
    Content = "å†™ç»™æ‚ æ‚ çš„å°ä¸–ç•Œã€‚"

 [params.profileMode]
  enabled = true
  title = "Yoyo's Blog"
  subtitle = "å†™ç»™æ‚ æ‚ çš„å°ä¸–ç•Œ ğŸ’›"
  imageUrl = ""
  imageWidth = 120
  imageHeight = 120


[[menu.main]]
  name = "ä¸»é¡µ"
  url = "/"
  weight = 1

[[menu.main]]
  name = "æ–‡ç« "
  url = "/posts/"
  weight = 2

